#!/usr/bin/env python3
"""
compute_velocity.py — RNA velocity estimation with scVelo.

Computes RNA velocity from spliced/unspliced counts in AnnData (.h5ad) format.
Supports stochastic and dynamical velocity models, with optional loom file input
for data generated by velocyto CLI.

Pipeline:
  1. scv.pp.filter_and_normalize — filter genes, normalize counts
  2. scv.pp.moments — compute first/second-order moments via KNN pooling
  3. scv.tl.velocity — estimate velocity (stochastic or dynamical)
  4. scv.tl.velocity_graph — build velocity transition graph
  5. scv.tl.velocity_embedding — project velocity onto low-dimensional embedding

Usage:
    python compute_velocity.py --input data.h5ad --output result.h5ad
    python compute_velocity.py --input data.h5ad --output result.h5ad --loom velocyto.loom
    python compute_velocity.py --input data.h5ad --output result.h5ad --mode dynamical --n_top_genes 3000
"""

import argparse
import sys
import warnings

warnings.filterwarnings("ignore")

try:
    import scvelo as scv
except ImportError:
    print("❌ scvelo 未安装，请执行: pip install scvelo>=1.0", file=sys.stderr)
    sys.exit(1)

try:
    import scanpy as sc
except ImportError:
    print("❌ scanpy 未安装，请执行: pip install scanpy", file=sys.stderr)
    sys.exit(1)

try:
    import anndata
except ImportError:
    print("❌ anndata 未安装，请执行: pip install anndata", file=sys.stderr)
    sys.exit(1)

import numpy as np


def load_data(input_path, loom_path=None):
    """
    Load AnnData from .h5ad. If a loom file is provided, read spliced/unspliced
    counts from it and merge into the AnnData object.
    """
    print(f"📂 读取数据: {input_path}")
    adata = sc.read(input_path)

    if loom_path is not None:
        print(f"📂 读取 loom 文件: {loom_path}")
        adata_loom = scv.read(loom_path, cache=False)

        # Merge spliced/unspliced layers from loom into existing adata
        # velocyto loom uses var_names as gene identifiers; align by intersection
        shared_genes = adata.var_names.intersection(adata_loom.var_names)
        if len(shared_genes) == 0:
            print("❌ loom 文件与 h5ad 文件无共享基因，请检查输入数据", file=sys.stderr)
            sys.exit(1)

        print(f"🧬 共享基因数: {len(shared_genes)}")
        adata_loom = adata_loom[:, shared_genes]
        adata = adata[:, shared_genes]

        adata.layers["spliced"] = adata_loom.layers["spliced"]
        adata.layers["unspliced"] = adata_loom.layers["unspliced"]

    # Validate layers
    has_spliced = "spliced" in adata.layers
    has_unspliced = "unspliced" in adata.layers
    if not (has_spliced and has_unspliced):
        print(
            "❌ h5ad 文件中缺少 'spliced' 和/或 'unspliced' 层。"
            "请使用 --loom 参数提供 velocyto 输出的 loom 文件，"
            "或确保数据由 velocyto/alevin-fry 生成。",
            file=sys.stderr,
        )
        sys.exit(1)

    return adata


def run_velocity(
    adata,
    mode="stochastic",
    n_top_genes=2000,
    n_pcs=30,
    n_neighbors=30,
    basis="umap",
):
    """
    Run the full scVelo velocity pipeline.

    Steps:
      1. Filter and normalize spliced/unspliced counts
      2. Compute first- and second-order moments
      3. Estimate RNA velocity
      4. Build velocity transition graph
      5. Project velocity onto embedding
    """
    print("🔬 步骤 1/5: 过滤与标准化 (filter_and_normalize)")
    scv.pp.filter_and_normalize(
        adata,
        min_shared_counts=20,
        n_top_genes=n_top_genes,
    )

    print(f"🔬 步骤 2/5: 计算矩 (moments) — n_pcs={n_pcs}, n_neighbors={n_neighbors}")
    scv.pp.moments(
        adata,
        n_pcs=n_pcs,
        n_neighbors=n_neighbors,
    )

    print(f"🔬 步骤 3/5: 估算 RNA velocity (mode={mode})")
    scv.tl.velocity(adata, mode=mode)

    print("🔬 步骤 4/5: 构建 velocity 转移图 (velocity_graph)")
    scv.tl.velocity_graph(adata)

    print(f"🔬 步骤 5/5: 投影 velocity 到 {basis} 嵌入 (velocity_embedding)")
    scv.tl.velocity_embedding(adata, basis=basis)


def main():
    parser = argparse.ArgumentParser(
        description="RNA velocity 计算 — scVelo pipeline",
    )
    parser.add_argument(
        "--input", "-i",
        required=True,
        help="输入 .h5ad 文件路径（需包含 spliced/unspliced 层，或配合 --loom 使用）",
    )
    parser.add_argument(
        "--output", "-o",
        required=True,
        help="输出 .h5ad 文件路径（velocity 结果将写入此文件）",
    )
    parser.add_argument(
        "--loom",
        default=None,
        help="velocyto 输出的 .loom 文件路径（如果 h5ad 不含 spliced/unspliced 层）",
    )
    parser.add_argument(
        "--mode",
        default="stochastic",
        choices=["stochastic", "dynamical"],
        help="velocity 模型: stochastic (默认) 或 dynamical",
    )
    parser.add_argument(
        "--n_top_genes",
        type=int,
        default=2000,
        help="高变基因数量 (默认: 2000)",
    )
    parser.add_argument(
        "--n_pcs",
        type=int,
        default=30,
        help="PCA 主成分数量 (默认: 30)",
    )
    parser.add_argument(
        "--n_neighbors",
        type=int,
        default=30,
        help="最近邻数量 (默认: 30)",
    )
    parser.add_argument(
        "--basis",
        default="umap",
        help="velocity 嵌入的降维基准 (默认: umap)",
    )

    args = parser.parse_args()

    # Load data
    adata = load_data(args.input, loom_path=args.loom)

    # Run velocity pipeline
    run_velocity(
        adata,
        mode=args.mode,
        n_top_genes=args.n_top_genes,
        n_pcs=args.n_pcs,
        n_neighbors=args.n_neighbors,
        basis=args.basis,
    )

    # Save results
    print(f"💾 保存结果到: {args.output}")
    adata.write(args.output)

    # Summary
    n_genes = adata.n_vars
    n_cells = adata.n_obs
    print(f"✅ RNA velocity计算完成: {n_genes}个基因, {n_cells}个细胞")


if __name__ == "__main__":
    main()
