export const SHARED_SKILLS = [
  "research-lookup",
  "literature-review",
  "pubmed-database",
  "biorxiv-database",
  "scientific-writing",
  "citation-management",
  "scientific-slides",
  "peer-review",
  "hypothesis-generation",
  "scientific-critical-thinking",
  "grill-me",
  "statistical-analysis",
  "exploratory-data-analysis",
  "matplotlib",
  "seaborn",
  "plotly",
] as const

const CORE: Record<string, readonly string[]> = {
  imc: [
    "imc-analysis",
    "pcf-analysis",
    "bioimage-analysis",
    "squidpy",
    "pathml",
    "histolab",
    "immunology-assays",
    "cellchat",
    "scanpy",
    "anndata",
    "imaging-data-commons",
    "omero-integration",
    "uniprot-database",
    "string-database",
  ],
  "single-cell": [
    "single-cell-pipeline",
    "scanpy",
    "anndata",
    "scvi-tools",
    "scvelo",
    "cellchat",
    "cellxgene-census",
    "pydeseq2",
    "umap-learn",
    "flow-cytometry-analysis",
    "flowio",
    "curated-bio-datasets",
    "geo-database",
    "gene-database",
  ],
  spatial: [
    "squidpy",
    "spatial-deconv",
    "scanpy",
    "anndata",
    "scvi-tools",
    "cellchat",
    "bioimage-analysis",
    "cellxgene-census",
    "gene-database",
    "imaging-data-commons",
  ],
  general: [
    "research-lookup",
    "literature-review",
    "pubmed-database",
    "openalex-database",
    "scientific-writing",
    "peer-review",
    "hypothesis-generation",
    "grill-me",
    "scientific-brainstorming",
    "statistical-analysis",
    "exploratory-data-analysis",
    "matplotlib",
    "biopython",
  ],
  genomics: [
    "biopython",
    "pysam",
    "deeptools",
    "gget",
    "cancer-genomics-analysis",
    "pydeseq2",
    "bioservices",
    "scikit-bio",
    "gtars",
    "dna-visualization",
    "ensembl-database",
    "clinvar-database",
    "cosmic-database",
    "gwas-database",
    "kegg-database",
    "reactome-database",
    "geo-database",
    "ena-database",
  ],
}

export function domainSkillAllowed(subdomain: string | undefined, name: string) {
  const id = subdomain && CORE[subdomain] ? subdomain : "general"
  return CORE[id].includes(name) || (SHARED_SKILLS as readonly string[]).includes(name)
}
